# Generated by Django 4.2.6 on 2023-10-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trip", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
