# Generated by Django 4.2.6 on 2023-10-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_groupchat_package_is_deleted_user_caution_cnt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_reply',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='is_completed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
