# Generated by Django 4.2.6 on 2023-10-23 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_groupchat_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='group_chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='trip.groupchat'),
        ),
    ]
