# Generated by Django 4.2.6 on 2023-10-23 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_package_is_deleted_user_caution_cnt_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='groupchat',
        ),
        migrations.DeleteModel(
            name='message',
        ),
    ]
