version: '3'

services:
  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: gunicorn --bind 0.0.0.0:8000 final.wsgi:application
      
  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    ports:
      - "6379:6379"