# Generated by Django 4.2.6 on 2023-10-31 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_postcomment_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='post_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='board.post'),
        ),
    ]
