# Generated by Django 4.2.6 on 2023-10-31 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_postcomment_post_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='post_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='board.post'),
        ),
    ]
