# Generated by Django 4.2.6 on 2023-10-31 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_postcomment_post_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['-create_at']},
        ),
    ]
